version: '3'
services:
  app:
    build: .
    container_name: ilinks-app
    ports:
      - "3001:3001"
    volumes:
      - ./server/ilinks.db:/app/server/ilinks.db
      - ./server/uploads:/app/server/uploads
    environment:
      - JWT_SECRET=please_change_this_secret_in_production
      - NODE_ENV=production
      - SERVE_STATIC=true
    restart: always
